/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package blog.brianthomas.immutables;

import java.util.Arrays;
import java.util.Date;

import blog.brianthomas.pojo.PojoAddress;
import blog.brianthomas.pojo.PojoPerson;

public class Main {
    public static void main(String... args) throws InstantiationException, IllegalAccessException {
    	Address address = ImmutableAddress.builder()
    			.number(123)
    			.street("Dogwood St.")
    			.city("Beverly Hills")
    			.state("CA")
    			.zip("90210").build();
    	Person p = ImmutablePerson.builder()
    			.name("Brian Thomas")
    			.addPhoneNumbers("123-456-7890")
    			.birthdate(new Date(2001, 10, 01))
    			.address(address)
    			.build();
    	
    	PojoPerson pp = new PojoPerson();
    	pp.setName("Brian Thomas");
    	pp.setPhoneNumbers(Arrays.asList("123-456-7890"));
    	pp.setBirthdate(new Date(2001, 10, 01));
    	PojoAddress pojoAddress = new PojoAddress();
    	pojoAddress.setNumber(123);
    	pojoAddress.setStreet("Dogwood St.");
    	pojoAddress.setCity("Beverly Hills");
    	pojoAddress.setState("CA");
    	pojoAddress.setZip("90210");
		pp.setAddress(pojoAddress);
		
		System.out.println(p);
		System.out.println(pp);
    }
    
    
}
